// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJgXT1L0Hwq_FiglG0glOoJqKw-x61l10',
    appId: '1:639284933812:web:3a7d436c784996357193e1',
    messagingSenderId: '639284933812',
    projectId: 'catatan-penjualan-b18bf',
    authDomain: 'catatan-penjualan-b18bf.firebaseapp.com',
    storageBucket: 'catatan-penjualan-b18bf.firebasestorage.app',
    measurementId: 'G-94VZ7ZR22J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXCpDU8vUxC2Lzr0h6f8I0mgd1vyRFVdc',
    appId: '1:639284933812:android:1aecbd25333373df7193e1',
    messagingSenderId: '639284933812',
    projectId: 'catatan-penjualan-b18bf',
    storageBucket: 'catatan-penjualan-b18bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6ghSq9vl8nmNI5ScikqKztphwUP66W90',
    appId: '1:639284933812:ios:8cf2abc86db803467193e1',
    messagingSenderId: '639284933812',
    projectId: 'catatan-penjualan-b18bf',
    storageBucket: 'catatan-penjualan-b18bf.firebasestorage.app',
    iosBundleId: 'com.example.catatanPenjualan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6ghSq9vl8nmNI5ScikqKztphwUP66W90',
    appId: '1:639284933812:ios:8cf2abc86db803467193e1',
    messagingSenderId: '639284933812',
    projectId: 'catatan-penjualan-b18bf',
    storageBucket: 'catatan-penjualan-b18bf.firebasestorage.app',
    iosBundleId: 'com.example.catatanPenjualan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJgXT1L0Hwq_FiglG0glOoJqKw-x61l10',
    appId: '1:639284933812:web:db718867a6a52c857193e1',
    messagingSenderId: '639284933812',
    projectId: 'catatan-penjualan-b18bf',
    authDomain: 'catatan-penjualan-b18bf.firebaseapp.com',
    storageBucket: 'catatan-penjualan-b18bf.firebasestorage.app',
    measurementId: 'G-JHCDT6X0GE',
  );
}
